### PR TITLE
Crossfilter and DC integration

### PR DESCRIPTION
**Pull request by yosiat**
Hi,

I have moved all charts from highcharts to crossfilter/dc for better performance and analysis.

In this pull request:
- Both charts are rendered using dc
- When you filter one charts all other get updated (and the table as well) - as a result you can filter by generation
- I have separated the code to it's own file and pretty-printed the html and the js

### CODE REVIEW

**Comment by yosiat** [comment]
I saw the type info pie chart is by count and not by sum of memsize, I can change this in this pull request or create another after this is merged.

**Comment by yosiat** [comment]
Rebased the branch, it's mergeable! :+1:

**Comment by gazay** [comment]
Hello, I've tried this PR with my dump, which is only ~110MB size, and there is an error: `Uncaught RangeError: Maximum call stack size exceeded` when I try to submit my file

**Comment by yosiat** [comment]
@gazay , Can you send me the call stack/dump file? It can be the file processing #8  or crossfilter.

**Comment by gazay** [comment]
I've tried when patched current master (with merged #8) with this PR. I'll send you file a little bit later

**Comment by gazay** [comment]
@yosiat https://www.dropbox.com/s/zj96mbpvaeheczh/dump.tar.gz?dl=0

**Comment by yosiat** [comment]
I found the problem, thanks for the dump file :+1: 
Objects with no-generation make crossfilter.dimension function run forever, I am working on fixing it righ tnow.

**Comment by yosiat** [comment]
Hi @gazay ,
I pushed a fix, can you look at it?

**Comment by gazay** [comment]
Hi, I'm on it. Btw can it be done without bower? I think @tenderlove don't want any server dependencies except simple index.html and maybe additional JS file in this project, because all point is that it works from gh-pages

**Comment by yosiat** [comment]
@gazay , This pull request dosen't have bower dependency (but #8 has).
I can copy the files, but I think @tenderlove meant that we don't want server-side for processing data, he want it to be on client side for ease of operation/scalability.

**Comment by gazay** [comment]
I see, I was just confused by `npm install bower` and `bower install`, but they are only for couple client side js files.

**Comment by gazay** [comment]
Looks good and works well. I miss an `Address` column and possibility to look at other properties of objects as `method`, `references` etc. And sorting. But that is good for different PRs

**Comment by gazay** [comment]
Also a bit different results in table if you chose Data type without changing generation and if you choose Type after you select all generations

**Comment by yosiat** [comment]
It would be great to peak into the hash and objects and not see references,
this project have lot of potential.

**Comment by yosiat** [comment]
Do you mean there is a different result by doing these operations?
1. Choosing DATA and no generations selected
2. Choosing DATA and all generations selected

**Comment by gazay** [comment]
Ah, I got it - there are a lot of objects without generation at all. Is it possible now to clear generations graphic range then?

screen shot 2015-10-01 at 1 03 39 am
screen shot 2015-10-01 at 1 04 14 am

**Comment by yosiat** [comment]
You can right click on the pie chart/bar chart and it will be cleared.
I will add stats and clears.

**Comment by tenderlove** [comment]
> I can copy the files, but I think @tenderlove meant that we don't want server-side for processing data, he want it to be on client side for ease of operation/scalability.

Correct, I don't want to do any server side processing.  I don't mind using Bower to set everything up (but I don't know how to use bower yet).

Should I merge this PR?

**Comment by tenderlove** [comment]
Meh, I'll just merge it. :)

**Pull request merged**
