### PR TITLE
Using w2grid for table

### PR DESCRIPTION
**Pull request by gazay**

### CODE REVIEW

**Comment by gazay** [comment]
Looks like this: 
screen shot 2015-09-19 at 7 02 26 pm
screen shot 2015-09-19 at 7 03 48 pm

**Comment by tenderlove** [comment]
Thanks for this, but can you change back the object parsing part? Before this change it would set up the object list and the index hash in one loop (which seems important for the number of objects we're dealing with).

**Comment by gazay** [comment]
You right, I've checked in profiler and it was twice slower than one cycle.

**Comment by gazay** [comment]
Do you want me to update screenshots for readme also?

**Comment by yosiat** [comment]
Hi @gazay,
This looks great, but I see there is a performance problem while showing large data set of objects.

Does w2ui support deferred rendering with paging like dataTables?https://datatables.net/reference/option/deferRender 

I have played dataTables and deferedRender and it improves performance a lot - it just render the first page and when you ask the other pages it renders them.

**Comment by gazay** [comment]
I'm not sure, I'm not really familiar with js and js libraries and technics, I've just googled tool for fast work with millions of rows. And this w2ui maybe renders first time not so fast, but then it allows you to fast sort and add/remove columns, easy render sub-tables and so on.

**Comment by gazay** [comment]
I'm closing it because of #9

**Comment by yosiat** [comment]
#9 dosen't imrpove the performance of the table renders, it's still slow as well.
I think we need to use data tables, because we must have first render time high perf, while you slice & dice - you redraw the table with huge amounts of data.

**Pull request closed without merging**
